jokes = [
    "I have an inferiority complex, but it’s not a very good one.",
    "I told my doctor that I broke my arm in two places. He told me to stop going to those places.",
    "What vegetable is cool, but not that cool? Rad-ish.",
    "I was wondering why the baseball kept getting bigger and bigger, and then it hit me.",
    "Why did the employee get fired from the calendar factory? She took a day off.",
    "Worrying works! Case in point: 90% of the things I worry about never happen.",
    "My teachers told me I’d never amount to much because I procrastinate. I told them, 'Just you wait!'",
    "Why do seagulls fly over the sea? If they flew over the bay, they would be bagels.",
    "I ordered a chicken and an egg from Amazon. I’ll let you know which comes first.",
    "What do you call a magician who lost his magic? Ian.",
    "I broke my finger last week. On the other hand, I am OK.",
    "I went to the doctor with a suspicious-looking mole. He told me they all look that way and I should have left it in the garden."
    "Two men are on opposite sides of the river. The first man shouts, “How do I get to the other side of the river?” The other man yells, “You are on the other side of the river!”",
    "Why would a pig dressed in black never get bullied? Because Batman has sworn to protect Goth-ham.",
    "Every morning, I announce that I’m going running, but then I don’t. It’s a running joke.",
    "Why is a swordfish’s nose 11 inches long? Because if it were 12 inches, it would be a foot.",
    "What state is known for its small drinks? Minnesota.",
    "What do you call a line of men waiting to get haircuts? A barberqueue.",
    "I was going to tell a time-traveling joke, but you didn’t like it.",
    "I can’t take my dog to the pond anymore because the ducks keep attacking him. That’s what I get for buying a pure bread dog.",
    "my wife and i laugh about how competitive we are. but i laugh more.",
    "how did the hipster burn his mouth? he ate his pizza before it was cool.",
    "i know they say money talks, but all mine says is "goodbye."",
    "why should you never fall in love with a tennis player? because to them, love means nothing!",
    "i gave up my seat to an elderly person on the bus. and that's how i lost my job as a bus driver.",
    "how do you find will smith in the snow? look for the fresh prints.",
    "do i know any jokes about sodium? na.",
    "70% of the earth is water, and virtually none of it is carbonated. so the earth is, in fact, flat.",
    "if you have six oranges in one hand and eight bananas in another, what do you have? big hands.",
    "my wife told me to stop impersonating a flamingo. i had to put my foot down.",
    "what did zero say to eight? nice belt.",
    "what's the difference between ignorance and apathy? i don't know, and i don't care.",
    "the past, the present and the future walked into a bar. it was tense.",
    "i just found out the company that produces yardsticks won't be making them any longer.",
    "geology rocks, but geography is where it's at.",
    "what's the difference between black-eyed peas and chickpeas? black eyed peas can sing us a song. chickpeas can hummus one.",
    "what did the duck say when she bought lipstick? put it on my bill.",
    "a termite walks into a bar. he says, "so, is the bar tender here?"",
    "did you hear that larry got a new job working for old macdonald? he's the new cieio.",
    "apparently, you can't use the words "beef stew" as a password. it's just not stroganoff."
]
