jokes = [
    "I have an inferiority complex, but it’s not a very good one.",
    "I told my doctor that I broke my arm in two places. He told me to stop going to those places.",
    "What vegetable is cool, but not that cool? Rad-ish.",
    "I was wondering why the baseball kept getting bigger and bigger, and then it hit me.",
    "Why did the employee get fired from the calendar factory? She took a day off.",
    "Worrying works! Case in point: 90% of the things I worry about never happen.",
    "My teachers told me I’d never amount to much because I procrastinate. I told them, 'Just you wait!'",
    "Why do seagulls fly over the sea? If they flew over the bay, they would be bagels.",
    "I ordered a chicken and an egg from Amazon. I’ll let you know which comes first.",
    "What do you call a magician who lost his magic? Ian.",
    "I broke my finger last week. On the other hand, I am OK.",
    "I went to the doctor with a suspicious-looking mole. He told me they all look that way and I should have left it in the garden."
    "Two men are on opposite sides of the river. The first man shouts, “How do I get to the other side of the river?” The other man yells, “You are on the other side of the river!”",
    "Why would a pig dressed in black never get bullied? Because Batman has sworn to protect Goth-ham.",
    "Every morning, I announce that I’m going running, but then I don’t. It’s a running joke.",
    "Why is a swordfish’s nose 11 inches long? Because if it were 12 inches, it would be a foot.",
    "What state is known for its small drinks? Minnesota.",
    "What do you call a line of men waiting to get haircuts? A barberqueue.",
    "I was going to tell a time-traveling joke, but you didn’t like it.",
    "I can’t take my dog to the pond anymore because the ducks keep attacking him. That’s what I get for buying a pure bread dog.",
    "my wife and i laugh about how competitive we are. but i laugh more.",
    "how did the hipster burn his mouth? he ate his pizza before it was cool.",
    'i know they say money talks, but all mine says is "goodbye."',
    "why should you never fall in love with a tennis player? because to them, love means nothing!",
    "i gave up my seat to an elderly person on the bus. and that's how i lost my job as a bus driver.",
    "how do you find will smith in the snow? look for the fresh prints.",
    "do i know any jokes about sodium? na.",
    "70% of the earth is water, and virtually none of it is carbonated. so the earth is, in fact, flat.",
    "if you have six oranges in one hand and eight bananas in another, what do you have? big hands.",
    "my wife told me to stop impersonating a flamingo. i had to put my foot down.",
    "what did zero say to eight? nice belt.",
    "what's the difference between ignorance and apathy? i don't know, and i don't care.",
    "the past, the present and the future walked into a bar. it was tense.",
    "i just found out the company that produces yardsticks won't be making them any longer.",
    "geology rocks, but geography is where it's at.",
    "what's the difference between black-eyed peas and chickpeas? black eyed peas can sing us a song. chickpeas can hummus one.",
    "what did the duck say when she bought lipstick? put it on my bill.",
    'a termite walks into a bar. he says, "so, is the bar tender here?"',
    "did you hear that larry got a new job working for old macdonald? he's the new cieio.",
    "apparently, you can't use the words “beef stew” as a password. it's just not stroganoff.",
    "what did one plate say to the other plate? dinner's on me.",
    "what did the janitor say when he jumped out of the closet? supplies!",
    "what do you call a lazy kangaroo? a pouch potato.",
    "i stayed up all night and tried to figure out where the sun was. then it dawned on me.",
    "why do bananas never get lonely? because they hang out in bunches.",
    "why did the student eat his homework? because the teacher told him it was a piece of cake.",
    "why did the doughnut go to the dentist? to get a filling.",
    "what do you call bears with no ears? b.",
    "who built king arthur's round table? sir cumference.",
    "what do you call a bear with no teeth? a gummy bear!",
    "why did the car get a flat tire? because there was a fork in the road.",
    "how many tickles does it take to make an octopus laugh? ten-tickles.",
    "how did the vikings communicate? with norse code.",
    "what do you call a fish with no eyes? a fsh.",
    "what do you call a well-dressed lion? a dandelion.",
    "what happens to a frog's car when it breaks down? it gets toad away.",
    "what kind of car does an egg drive? a yolkswagen.",
    "there were two muffins in an oven, and one said, “it's getting hot in here, isn't it?” the other muffin gasped, “aah! a talking muffin!”",
    "what was beethoven's favorite fruit? a ba-na-na-na.",
    "what do you call a female chicken staring at a pile of lettuce? a chicken caesar salad.",
    "how do trees access their email? they log in.",
    "why don’t scientists trust atoms? they make up everything.",
    "which program do jedi use to sign their files? adobe sign kenobi.",
    "what is the best way to criticize your boss? very quietly, so she cannot hear you.",
    "our computers went down at the office today, so we had to do everything manually. it took me 15 minutes to shuffle the cards for solitaire.",
    "how do folks at nasa organize a party? they planet.",
    "why don’t comedians tell unemployment jokes? none of them work.",
    "why does snoop dogg use an umbrella? fo drizzle.",
    "how many computer programmers does it take to change a light bulb? none—that’s a hardware issue.",
    "a salesperson came into an office one day and said, “this computer will cut your workload by 50%!” the office manager replied, “great, i’ll take two of them!”",
    "what do you call someone who is happy on mondays? unemployed.",
    "what do you call 12 people doing the work of one? a committee.",
    "why didn’t the terminator upgrade to windows 10? i asked him and he said, “i still love vista, baby.”",
    "to the person who stole my copy of microsoft office, i will find you. you have my word.",
    "what kind of award does the world’s top dentist get? a little plaque.",
    "to err is human. to blame it on someone else shows management potential.",
    "if it wasn’t for the last minute, nothing would get done.",
    "archaeologist: someone whose career lies in ruins.",
    "the trouble with being punctual is that nobody’s there to appreciate it.",
    "i think they picked me for my motivational skills. everyone always says they have to work twice as hard when i’m around!",
    "have you heard about the guy who stole the calendar? he got 12 months!",
    "why does the golfer wear two pairs of pants? because he’s afraid he might get a hole in one.",
    "i’m so good at sleeping that i can do it with my eyes closed!",
    "why is it impossible to starve in the desert? because of all the sand which is there.",
    "two antennas decided to get married. the ceremony was pretty boring, but the reception was great!",
    "why shouldn’t you tell secrets in a cornfield? too many ears.",
    "what does a vegan zombie like to eat? graaains.",
    "what’s the difference between a well-dressed cyclist and a scruffy guy on a tricycle? a tire.",
    "what did the buddhist ask the hot dog vendor? make me one with everything.",
    "what do you call a pigeon who can’t find his way home? a pigeon.",
    "my wife told me to take the spider out instead of killing him, so i did. we went out, had a few drinks, saw a movie. great guy.",
    "how many sailors are pirates? 3.14%.",
    "i like telling dad jokes. sometimes he even laughs.",
    "what did one frenchman say to the other? no idea, i don’t speak french.",
    "i was raised as an only child—and that got on my brother’s nerves.",
    "why don’t vampires bet on horses? they can’t handle the stakes.",
    "a man rushed into a doctor’s surgery, shouting, “help me, please! i’m shrinking!” the doctor calmly said, “now settle down a bit. you’ll just have to learn to be a little patient.”",
    "do you know where you can get chicken broth in bulk? the stock market.",
    "what’s the best part about living in switzerland? i don’t know, but the flag is a big plus.",
    "have you heard the rumor about butter? never mind, i shouldn’t be spreading it."
]
